[package]
name = "water-sort-cli"
version.workspace = true
edition.workspace = true

[features]
default = [
    "hidable_items",
    "lockable_items",
    "immovable_bottles",
    "pluggable_bottles",
    "freezable_bottles",
    "curtains",
    "safes",
    "lock_groups",
    "colored_bottles",
    "color_curtains",
]

hidable_items = ["water-sort-core/hidable_items"]
lockable_items = ["water-sort-core/lockable_items"]
immovable_bottles = ["water-sort-core/immovable_bottles"]
pluggable_bottles = ["water-sort-core/pluggable_bottles"]
freezable_bottles = ["water-sort-core/freezable_bottles"]
curtains = ["water-sort-core/curtains"]
safes = ["water-sort-core/safes"]
lock_groups = ["water-sort-core/lock_groups"]
colored_bottles = ["water-sort-core/colored_bottles"]
color_curtains = ["water-sort-core/color_curtains"]

[dependencies]
clap = { version = "4.6", features = ["derive"] }
serde_json = { workspace = true }
water-sort-core = { workspace = true }
